postgres9:
  image: postgres:9.4
  ports:
    - 5432:5432
  volumes_from:
    - pg_data
    - dat
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    PGDATA : /var/lib/postgresql/data/pgdata

pg_data:
  image: alpine:latest
  volumes:
    - ./data:/var/lib/postgresql/data/pgdata
  command: "true"

dat:
  image: alpine:latest
  volumes:
    - ./src:/src
  command: "true"

# add comments liberally